data_transforms:
  a_min: 0
  a_max: 255
  img_size: 256
  use_random_crop: False
  use_rotation: True
  rotation_angle: 10
  use_saturation: True
  saturation: 2
  use_brightness: True
  brightness: 2
  use_horizontal_flip: False
data:
  name: ENDOVIS
  root_path: '/media/ubuntu/New Volume/jay/endovis17/all_training'
  label_list: [1,2,3,4,5,6,7,8,9]
  label_names: ['Left Prograsp Forceps', 'Maryland Bipolar Forceps', 'Right Prograsp Forceps', 'Left Large Needle Driver', 'Right Large Needle Driver', 'Left Grasping Retractor', 'Right Grasping Retractor', 'Vessel Sealer', 'Monopolar Curved Scissors']
  volume_channel: 2
